%% main
clear all
close all
% Parameter Multimodefibre
NA=0.1;
nCore = 1.4607;                 % at 20 deg C -> Pure Silica/ fused Silica
nCladding = sqrt(nCore^2-NA^2); % 1.4440375;      % at 20 deg C -> Fluorine-Doped Silica  
wavelength = 0.532;             % in um
coreRadius = 25/2;              % in um

% Modesolver parameters -> build modes
gridSize = 32;             % gridsize for modesolver; Wert am:06.04: 50

mode_target=2;             % which mode should be generated by SLM?
% if exist('mode_target_distribution.mat', 'file') == 2
%     load('mode_target_distribution.mat');
% else
modes=build_modes(nCore,nCladding,wavelength,coreRadius,gridSize);
mode_target_distribution=squeeze(modes(mode_target,:,:));
%save('mode_target_distribution.mat', 'mode_target_distribution');
% end

% load('optical_beam');

N_it = 10; % Anzahl der Iterationen
holo_size = 600;
input_phase = rand(holo_size, holo_size) * 2*pi - pi;
input_amp = ones(holo_size, holo_size)/100000;

input = input_amp .* exp(1i*input_phase);

for i=1:N_it
    input_fft = fftshift(fft2(input));

    input_fft_amp = abs(input_fft);
    input_fft_phase = angle(input_fft);
    
    start = holo_size / 2 - gridSize / 2;
    stop = holo_size / 2 + gridSize / 2 - 1;
    input_fft_amp(start:stop, start:stop) = abs(mode_target_distribution);
    input_fft_phase(start:stop, start:stop) = angle(mode_target_distribution);

    input_fft_complete = input_fft_amp .* exp(1i*input_fft_phase);

    target = ifft2(ifftshift(input_fft_complete));
    % target_shifted = fftshift(target);
    input = input_amp .* exp(1i*angle(target));
end

gs_mask = input;
modulated_input = fftshift(fft2(input));
figure;
subplot(3, 2, 1);
imagesc(abs(mode_target_distribution));title('Amplitude of mode target distribution'); axis image
subplot(3, 2, 2);
imagesc(angle(mode_target_distribution));title('Phase of mode target distribution'); axis image
subplot(3, 2, 3);
imagesc(abs(modulated_input));title('Amp moduliert nach fft'); axis image
subplot(3, 2, 4);
imagesc(angle(modulated_input));title('Phase moduliert nach fft'); axis image
subplot(3, 2, 5);
imagesc(abs(gs_mask));title('Amp maske'); axis image
subplot(3, 2, 6);
imagesc(angle(gs_mask));title('Phase maske'); axis image
