%% main
% Parameter Multimodefibre
NA=0.1;
nCore = 1.4607;                 % at 20 deg C -> Pure Silica/ fused Silica
nCladding = sqrt(nCore^2-NA^2); % 1.4440375;      % at 20 deg C -> Fluorine-Doped Silica  
wavelength = 0.532;             % in um
coreRadius = 25/2;              % in um

% Modesolver parameters -> build modes
gridSize = 800;             % gridsize for modesolver; Wert am:06.04: 50
% modes=build_modes(nCore,nCladding,wavelength,coreRadius,gridSize);
% mode_target=14;             % which mode should be generated by SLM?
% mode_target_distribution=squeeze(modes(mode_target,:,:)); % select mode generated by SLM
load('mode_target_distribution');

% SLM & Superpixel parameters  
bitDepthSLM = 8;            % Bit
m_SLM=800;      % Y-axis
n_SLM=800;      % X-axis    -> number SLM pixel
                %           -> Phasemask will be put into center of SLM
%% Preparation of Mask with Gerchberg-Saxton

% area in which the generated field quality will be analyzed 
[X,Y]=meshgrid(1:n_SLM,1:m_SLM);
area_analysis=false(n_SLM,m_SLM); % müssen noch nen bereich auf true setzen

gs_mask = dcgs(optical_beam, mode_target_distribution);
%% Start modulation
load('optical_beam');   %simuliere einen Gaußschen Laserstrahl

modulated_beam=optical_beam.*exp(1i*gs_mask);   %der Laserstrahl trifft auf die SLM Oberfläche

% modulierter Laserstrahl propagiert durch Linse -> FFT
modulated_beam_fft=fftshift(fft2(modulated_beam));  % L1
% figure;imagesc(abs(modulated_beam_fft));
%% Visualisierung

figure;
subplot(2,2,1);
imagesc(abs(mode_target_distribution));title('Gewünschte Amplitudenverteilung');axis image
subplot(2,2,2);
imagesc(angle(mode_target_distribution));title('Gewünschte Phasenverteilung');axis image
subplot(2,2,3);
imagesc(abs(modulated_beam_fft));title('Modulierte Amplitudenverteilung');axis image
subplot(2,2,4);
imagesc(angle(modulated_beam_fft));title('Modulierte Phasenverteilung');axis image