%% main
clear all
% Parameter Multimodefibre
NA=0.1;
nCore = 1.4607;                 % at 20 deg C -> Pure Silica/ fused Silica
nCladding = sqrt(nCore^2-NA^2); % 1.4440375; at 20 deg C -> Fluorine-Doped Silica  
wavelength = 0.532;             % in um
coreRadius = 25/2;              % in um

desired_beam_size = 200;
gridSize = 80;

modes = build_modes(nCore, nCladding, wavelength, coreRadius, gridSize);
mode_target = 1;             % which mode should be generated by SLM?
mode_target_distribution = squeeze(modes(mode_target,:,:));
load('optical_beam');
optical_beam = imresize(optical_beam, 200/800);

[slm_mask, mask] = my_dcgs(optical_beam, mode_target_distribution);

modulated = optical_beam .* exp(1i*slm_mask);

res = fftshift(fft2(modulated));

figure;imagesc(slm_mask);axis image
figure;imagesc(abs(res .* mask));axis image
figure;imagesc(angle(res .* mask));axis image
    
