% main
clear all
close all
% Parameter Multimodefibre
NA=0.1;
nCore = 1.4607;                 % at 20 deg C -> Pure Silica/ fused Silica
nCladding = sqrt(nCore^2-NA^2); % 1.4440375; at 20 deg C -> Fluorine-Doped Silica  
wavelength = 0.532;             % in um
coreRadius = 25/2;              % in um

gridSize = 50;
bit_res = 8;
modes = build_modes(nCore, nCladding, wavelength, coreRadius, gridSize);
mode_target = 2;             % which mode should be generated by SLM?
mode_target_distribution = squeeze(modes(mode_target,:,:));

% discretizes the phase
phase_values = linspace(-pi, pi, 2^bit_res);
phase_step = abs(phase_values(1) - phase_values(2));

start_phase = phase_values(1) - phase_step/2;
stop_phase = start_phase + 2^bit_res * phase_step;
phase_edges = start_phase:phase_step:stop_phase;

holo = ifft2(mode_target_distribution);
disc_holo_phase = discretize(angle(holo), phase_edges, phase_values);
disc_holo = abs(holo) .* exp(1i*disc_holo_phase);
noisy_mode = fft2(disc_holo);
mode = fft2(holo);

% figure; imagesc(abs(mode_target_distribution));
% figure; imagesc(angle(mode_target_distribution));
figure; imagesc(abs(holo)); title('amp normal holo');
figure; imagesc(angle(holo)); title('phase normal holo');
figure; imagesc(abs(mode));title('amp normal mode');
figure; imagesc(angle(mode));title('phase normal mode');
figure; imagesc(abs(disc_holo)); title('amp disc holo');
figure; imagesc(angle(disc_holo)); title('phase disc holo');
figure; imagesc(abs(noisy_mode));title('amp disc mode');
figure; imagesc(angle(noisy_mode));title('phase disc mode');
figure; imagesc(angle(holo)-disc_holo_phase);title('disc fehler');
figure; imagesc(abs(holo)-abs(disc_holo));title('amp fehler');